export enum KafkaEventsMessagingEnum {
  CREATE_PROFILE = 'CREATE_PROFILE',
  UPDATE_PROFILE = 'UPDATE_PROFILE',
  DELETE_PROFILE = 'DELETE_PROFILE',
  GET_PROFILE = 'GET_PROFILE',
  GET_ALL_PROFILES = 'GET_ALL_PROFILES',
  GET_PROFILE_BY_ID = 'GET_PROFILE_BY_ID',
  GET_PROFILE_BY_EMAIL = 'GET_PROFILE_BY_EMAIL',
  GET_PROFILE_BY_NATIONAL_CODE = 'GET_PROFILE_BY_NATIONAL_CODE',
}
